on:
  release:
    types:
      - created

name: release
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2

      - id: release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: build
        run: |
          GOOS=linux GOARCH=amd64 go build -ldflags "-X 'main.Version=${{ steps.release.outputs.tag_name }}'" -o ego ./cmd/ego
          tar -czvf ego-${{ steps.release.outputs.tag_name }}-linux-amd64.tar.gz ego
          
          GOOS=darwin GOARCH=amd64 go build -ldflags "-X 'main.Version=${{ steps.release.outputs.tag_name }}'" -o ego ./cmd/ego
          tar -czvf ego-${{ steps.release.outputs.tag_name }}-darwin-amd64.tar.gz ego

      - name: upload linux
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./ego-${{ steps.release.outputs.tag_name }}-linux-amd64.tar.gz
          asset_name: ego-${{ steps.release.outputs.tag_name }}-linux-amd64.tar.gz
          asset_content_type: application/gzip

      - name: upload darwin
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./ego-${{ steps.release.outputs.tag_name }}-darwin-amd64.tar.gz
          asset_name: ego-${{ steps.release.outputs.tag_name }}-darwin-amd64.tar.gz
          asset_content_type: application/gzip
